export const FETCH_CHECKOUT = "FETCH_CHECKOUT";

export const FETCH_ORDER_ITEMS = "FETCH_ORDER_ITEMS";

export const ADD_TO_CART = "ADD_TO_CART";

export const FETCH_ORDER_LIST = "FETCH_ORDER_LIST";

export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";

export const DELETE_ORDER = "DELETE_ORDER";

export const EDIT_ORDER = "EDIT_ORDER";

export const SHOW_ORDER_FORM = "SHOW_ORDER_FORM";

export const CLOSE_ORDER_FORM = "CLOSE_ORDER_FORM";
