export const TOGGLE_FORM_UPDATE = "TOGGLE_FORM_UPDATE";

export const FETCH_ACCOUNT_UPDATE_INFO = "FETCH_ACCOUNT_UPDATE_INFO";

export const FETCH_PRODUCT_UPDATE_INFO = "FETCH_PRODUCT_UPDATE_INFO";

export const FETCH_ORDER_UPDATE_INFO = "FETCH_ORDER_UPDATE_INFO";
