export const FETCH_PRODUCT_LIST = "FETCH_PRODUCT_LIST";

export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";

export const INC_PROD_QTY = "INC_PROD_QTY";

export const DEC_PROD_QTY = "DEC_PROD_QTY";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const SHOW_PRODUCT_FORM = "SHOW_PRODUCT_FORM";

export const CLOSE_PRODUCT_FORM = "CLOSE_PRODUCT_FORM";
