#!/bin/bash

installNodeModules() {
    echo "Install node_modules"
    yarn
    (cd ./frontend/ && yarn)
    (cd ./backend/ && yarn)
}

devApp() {
    echo "Run app"
    (cd ./frontend/ && yarn dev)
    (cd ./backend/ && yarn dev)
}

# pkill vite

# rm -rf frontend/node_modules/.vite

devApp
